name: stitching
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11.*
  - pytorch>=2.2.1
  - pytorch-cuda>=11.8
  - pycudadecon
  - pyvista
  - psutil
  - tqdm
  - tifffile
  - imageio
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pywavelets
  - matplotlib
  - pandas
  - pillow
  - colorama
  - imagecodecs>=2023.7.10
  - freeimage
  - git
  - mpi4py=3.1.5
  - cmake
  - numba
  - numexpr>=2.8.4
  - jupyter
  - ipykernel
  - py-opencv=4.8.*
  - pynrrd
  - ffmpeg
  - tensorly
  - pip
  - pip:
      - imaris_ims_file_reader
      - dcimg
      - cpufeature
      - ptwt
